project/apps/main/urls.py
from project.apps.main import views

__author__ = 'dotaxlevel'

from django.conf.urls import patterns, url

urlpatterns = patterns('',
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>\d+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^(?P<pk>\d+)/results/$', views.ResultsView.as_view(), name='results'),
    url(r'^(?P<question_id>\d+)/vote/$', views.vote, name='vote'),
)

project/base/urls.py
from django.conf.urls import patterns, include, url
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns("",
                   url(r'^$', include('project.apps.main.urls', namespace='main')),
                   #(r'^accounts/', include('allauth.urls')),

                   #admin
                   url(r'^admin/', include(admin.site.urls)),)+staticfiles_urlpatterns()

project/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'project.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
)

project/apps/main/models.py
import datetime

from django.db import models
from django.utils import timezone

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently'


class Choice(models.Model):
    question = models.ForeignKey(Question)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

project/apps/todo/models.py
from django.db import models


class DateTime(models.Model):
    datetime = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return unicode(self.datetime)


class Item(models.Model):
    name = models.CharField(max_length=60)
    created = models.ForeignKey(DateTime)
    priority = models.IntegerField(default=0)
    difficulty = models.IntegerField(default=0)
    done = models.BooleanField(default=False)

project/apps/main/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.views import generic

from project.apps.main.models import Choice, Question

class IndexView(generic.ListView):
    template_name = 'main/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        return Question.objects.order_by('-pub_date')[:5]


class DetailView(generic.DetailView):
    model = Question
    template_name = 'main/detail.html'


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'main/results.html'


def vote(request, question_id):
    p = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = p.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        return render(request, 'main/detail.html', {
            'question': p,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        return HttpResponseRedirect(reverse('polls:results', args=(p.id,)))

project/apps/todo/views.py
from django.utils.translation import ugettext as _
from django.shortcuts import render

project/base/views.py
# -*- coding: utf-8 -*-
from django.template.response import TemplateResponse

def index(request):
  return TemplateResponse(request , 'admin/index.html', {})

project/apps/main/templates/main/detail.html
{% extends "layout.html" %}

{% block title %}Details: {{ question.question_text }}{% endblock %}
{% block content %}
    <h1>{{ question.question_text }}</h1>

    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

    <form action="{% url 'main:vote' question.id %}" method="post">
    {% csrf_token %}
    {% for choice in question.choice_set.all %}
        <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
        <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
    {% endfor %}
    <input type="submit" value="Vote" />
    </form>
{% endblock %}

project/apps/main/templates/main/index.html
{% extends "base.html" %}

{% block header %}Header #2: custom{% endblock %}

{% block title %}Questins: {{ latest_question_list.count }}{% endblock %}

{% block content %}
    {% if latest_question_list %}
        <ul>
        {% for question in latest_question_list %}
            <li><a href="{% url 'main:detail' question.id %}">{{ question.question_text }}</a></li>
        {% endfor %}
        </ul>
    {% else %}
        <p>No polls are available.</p>
    {% endif %}
{% endblock %}

{% block footer %}footer #2: custom{% endblock %}

project/apps/main/templates/main/results.html
{% extends "layout.html" %}

{% block title %}Results: {{ question.question_text }}{% endblock %}

{% block content %}
    <h1>{{ question.question_text }}</h1>

    <ul>
    {% for choice in question.choice_set.all %}
        <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
    {% endfor %}
    </ul>

    <a href="{% url 'main:detail' question.id %}">Vote again?</a>
{% endblock %}

project/apps/todo/templates/main/index.html
{% extends "base.html" %}

{% block header %}Header #2: custom{% endblock %}

{% block title %}Questins: {{ latest_question_list.count }}{% endblock %}

{% block content %}
    {% if latest_question_list %}
        <ul>
        {% for question in latest_question_list %}
            <li><a href="{% url 'main:detail' question.id %}">{{ question.question_text }}</a></li>
        {% endfor %}
        </ul>
    {% else %}
        <p>No polls are available.</p>
    {% endif %}
{% endblock %}

{% block footer %}footer #2: custom{% endblock %}

project/apps/todo/templates/todo/index.html
{% extends "base.html" %}

{% block title %}TODO - List{% endblock %}

{% block content %}
    {% if latest_question_list %}
        <ul>
        {% for question in latest_question_list %}
            <li><a href="{% url 'main:detail' question.id %}">{{ question.question_text }}</a></li>
        {% endfor %}
        </ul>
    {% else %}
        <p>No polls are available.</p>
    {% endif %}
{% endblock %}

templates/_partials/javascript-core.html
<script src="{{ STATIC_URL }}js/libs/jquery-1.11.1.min.js" type="text/javascript" charset="utf-8"></script>

templates/_partials/main_nav.html
<ul>
    <li><a href="#" class="btn btn-danger">Main</a></li>
    <li><a href="#" class="btn btn-danger">Map</a></li>
    <li><a href="#" class="btn btn-danger">Info</a></li>
    <li><a href="#" class="btn btn-danger">Report to developers</a></li>
</ul>

templates/_partials/stylesheet-core.html
<link rel="stylesheet" href="{{ STATIC_URL }}css/vendor/bootstrap.min.css" type="text/css" charset="utf-8">

templates/base.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{% block title %}Main page{% endblock %}</title>
    {% include "_partials/stylesheet-core.html" %}
    {% block stylesheet_custom %}{% endblock %}
</head>
<body>
<div class="container">
    <header>{% block header %}{% endblock %}</header>
    <nav>{% block nav %}{% include "_partials/main_nav.html" %}{% endblock %}</nav>
    <section>{% block content %}{% endblock %}</section>
    <footer>{% block footer %}{% endblock %}</footer>
</div>

{% include "_partials/javascript-core.html" %}
{% block javascript_custom %}
    <script type="text/javascript">
        $(document).ready(function () {
            console.log('initialize');
        });
    </script>
{% endblock %}
</body>
</html>